environment:
  PYTHON_HOME: "C:\\Python37"

  matrix:
    - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Debug
    - MINGW_CONFIGURATIONS: "4.9@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Release
    - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Debug
    - MINGW_CONFIGURATIONS: "5@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Release
    - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Debug
    - MINGW_CONFIGURATIONS: "6@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Release
    - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Debug
    - MINGW_CONFIGURATIONS: "7@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Release
    - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Debug
    - MINGW_CONFIGURATIONS: "8@x86_64@seh@posix"
      CONAN_BUILD_TYPES: Release
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Debug
      CONAN_CMAKE_GENERATOR: Ninja
      CC: cl.exe
      CXX: cl.exe
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      CONAN_VISUAL_VERSIONS: 14
      CONAN_BUILD_TYPES: Release
      CONAN_CMAKE_GENERATOR: Ninja
      CC: cl.exe
      CXX: cl.exe

install:
  - set PATH=%PYTHON_HOME%;%PYTHON_HOME%/Scripts/;%PATH%
  - pip install conan --upgrade
  - pip install bincrafters_package_tools
  - conan user

build_script:
  - python build.py
